### PR TITLE
linux32

### PR DESCRIPTION
**Pull request by jayenashar**
couldn't figure out how to detect 32-bit on travis
didn't see a need to change jmh
couldn't get ByteArrayComparator working

### CODE REVIEW

**Comment by krisskross** [comment]
I'm not sure I want to take this PR. Releasing and supporting 32-bit artifacts would be a hassle.

I'm open to support 32-bit it if we can automate the procedure through travis but I don't have time to spend on this now. But please take a stab if you want.

**Comment by jayenashar** [comment]
I'd love to take a stab at Travis, but haven't got the time right now either.  Would you be open to adding a mention in your readme?

**Comment by krisskross** [comment]
Not sure what you want mentioned? Issue #63 is about automating maven releases. We could add a comment on linux32 also?

**Comment by jayenashar** [comment]
If you're open to adding a mention, then I would worry about what to mention.  Probably if I push the linux32 to maven, you could add a maven block for it?  I would probably only push 0.4.6 and not earlier versions.  If you have a different suggestion for people to use linux32 without building from source, I'm open to it, but I think what I mention above is relatively easy for all parties involved.

Thanks for the link to #63.  If I get time to learn how to configure/use Travis, I'll have a look at that one as well.

**Pull request closed without merging**
